### ISSUE TITLE
branch: radio-buttons-test

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/under-pressure#120]
Please describe or delete if no longer necessary.

**Comment by aaronsamuel137** [comment]
This branch was created when @samreid and I were working on the new radio buttons and wanted to see if they would look better in under-pressure than the current radio buttons.

I recommend we delete both this branch and radiobuttons, because even if we want to replace the radio buttons in under-pressure, it will probably be easier just to start from current master. Before I do, I want to check with @samreid, since he worked on this with me.

**Comment by samreid** [comment]
Master has the latest and greatest radio buttons, I deleted the branch, closing.
