### ISSUE TITLE
Win 7 IE11 slider artifacts

### ISSUE THREAD

**Issue by phet-steele** [phetsims/under-pressure#142]
Very noticeable artifacts on the Gravity slider. Below screenshot was from dragging to the right (starting at Mars). It appears as one artifact because I was dragging slowly. Quicker dragging shows more distinct artifacts. @aadish seen on our device named Bates, and again Win 7 IE11. For phetsims/tasks/issues/591.

![20160516_103957](https://cloud.githubusercontent.com/assets/5863899/15296645/87814f92-1b53-11e6-9cab-f0d77614856e.jpg)

**Comment by phet-steele** [comment]
Fixed!!

**Comment by pixelzoom** [comment]
@aadish We're seeing a similar problem with artifacts in https://github.com/phetsims/plinko-probability/issues/93.  I inspected your commit @46c9948a5445d2374198db6fb726accc474a385c. Could you please elaborate on how this change fixed the artifacts issue?

**Comment by aadish** [comment]
@pixelzoom I was trying to look what was the abnormal thing in the code when I was creating the HSlider and was just playing around with it and deleting the maxWidth did the trick. 

I don't have a sound reasoning behind it but think that in IE setting up minWidth and maxWidth messes up things around 

I tried modifying the code in LabScreenView for PlinkProbability

```js
// controls that modify the pegs in the galton board, below the Play panel
    var pegControls = new PegControls( model.numberOfRowsProperty, model.probabilityProperty, {
      minWidth: PANEL_FIXED_WIDTH,
      //maxWidth: PANEL_FIXED_WIDTH,
      top: playPanel.bottom + PlinkoProbabilityConstants.PANEL_VERTICAL_SPACING,
      right: playPanel.right
    } );
```
Commented maxWidth and it worked well in Explorer. 

Might be good idea to look in the scenery graph what happens when maxWidth and minWidth are specified together

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/under-pressure/issues/142#issuecomment-248451321, @aadish said:
> I don't have a sound reasoning behind it but think that in IE setting up minWidth and maxWidth messes up things around

@jonathanolson Any reason why this scenery feature might cause problems in IE?

**Comment by pixelzoom** [comment]
Thanks @aadish. Closing. I'll continue to work on https://github.com/phetsims/plinko-probability/issues/93.
